DZ1/DZ1/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path

from MMB.views import MembersView, MemberView, BandsView, BandView, registration, login, TitlesView, \
    logoutView, ProfileView, UpdateProfileView, BandListView #, UpdateAvaView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', login),
    url(r'^member/$', MembersView.as_view()),
    url(r'^member/(?P<id>\d+)$', MemberView.as_view(), name='member_url'),
    url(r'^band/page=(?P<page>\d+)', BandsView.as_view()),
    url(r'^band/(?P<id>\d+)$', BandView.as_view(), name='band_url'),
    url(r'^logout/', logoutView, name='logout'),
    url(r'^login/', login),
    url(r'^registration/', registration),
    url(r'^start/', TitlesView.as_view()),
    url(r'^profile/', ProfileView.as_view()),
    url(r'^update_profile/', UpdateProfileView.as_view()),
    url(r'^bands/', BandListView.as_view(), name='home'),
    #url(r'^update_ava/', UpdateAvaView.as_view())
    # url(r'^me/', CustomerInDetail.as_view(), name='customers_detail')
]

DZ1/MMB/models.py
from django.db import models

from django.contrib.auth.models import User


class MemberModel(models.Model):
    class Meta:
        db_table = 'member'

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    birthdate = models.DateField()
    deathdate = models.DateField(null=True, blank=True)
    country = models.CharField(max_length=30)
    photo = models.FileField(default='static/media/default.jpg', upload_to='static/media/', blank=True)


def __str__(self):
    return self.last_name


class BandModel(models.Model):
    class Meta:
        db_table = 'band'

    name = models.CharField(max_length=30)
    members = models.ManyToManyField(MemberModel, through='MembershipModel', null=True, blank=True)
    genre = models.CharField(max_length=50)
    history = models.CharField(max_length=255, null=True, blank=True)
    pic = models.FileField(default='static/media/default.jpg', upload_to='static/media/')


def __str__(self):
    return self.name


class MembershipModel(models.Model):
    class Meta:
        db_table = 'membership'

    id_member_FK = models.ForeignKey(MemberModel, on_delete=models.CASCADE, db_column='id_member_FK',
                                     related_name='id_member_FK')
    id_band_FK = models.ForeignKey(BandModel, on_delete=models.CASCADE, db_column='id_band_FK',
                                   related_name='id_band_FK')
    function = models.CharField(max_length=50)
    statuss = models.BooleanField(default=1)


def __str__(self):
    return "Band: {}, Member: {}".format(self.id_band_FK, self.id_member_FK)


'''class UserModel(models.Model):
    class Meta:
        db_table = 'avatar'

#    nameofuser = models.OneToOneField(User, models.CASCADE, primary_key=True, db_column='nameofuser',
#                                      related_name='nameofuser')
#    ava = models.FileField(default='static/media/ava/default.jpg', upload_to='static/media/ava/')
    nameofuser = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='static/media/default.jpg', upload_to='static/media/ava/')

def __str__(self):
    return "User: {}, Avatar: {}".format(self.nameofuser, self.ava)'''

DZ1/MMB/forms.py
from datetime import date

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from MMB.models import BandModel, MemberModel, MembershipModel #, UserModel


class LoginForm(forms.Form):
    """ Base class for authenticating users. Extend this to get a form that accepts
    username/password logins. """
    username = UsernameField(
        label='Логин',
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}),
    )
    password = forms.CharField(
        label='Пароль',
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )


class RegistrationForm(forms.Form):
    username = forms.CharField(min_length=5, label='Логин')
    password = forms.CharField(min_length=8, widget=forms.PasswordInput, label='Пароль')
    password2 = forms.CharField(min_length=8, widget=forms.PasswordInput, label='Повторите пароль')
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')
    avatar = forms.ImageField(label='Аватар')

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'type': 'email', 'class': 'form-control',
                                                     'id': 'exampleInputEmail1', 'aria-describedby': 'emailHelp',
                                                     'placeholder': 'Введите Логин'})

        self.fields['password'].widget.attrs.update({'type': 'password', 'class': 'form-control',
                                                     'id': 'exampleInputPassword1', 'placeholder': 'Пароль'})

        self.fields['password2'].widget.attrs.update({'type': 'password', 'class': 'form-control',
                                                      'id': 'exampleInputPassword1', 'placeholder': 'Повторите пароль'})

        self.fields['email'].widget.attrs.update({'type': 'email', 'class': 'form-control',
                                                  'id': 'exampleInputEmail1', 'aria-describedby': 'emailHelp',
                                                  'placeholder': 'Введите Email'})

        self.fields['first_name'].widget.attrs.update({'type': 'email', 'class': 'form-control',
                                                       'id': 'exampleInputEmail1', 'aria-describedby': 'emailHelp',
                                                       'placeholder': 'Введите Имя'})

        self.fields['last_name'].widget.attrs.update({'type': 'email', 'class': 'form-control',
                                                      'id': 'exampleInputEmail1', 'aria-describedby': 'emailHelp',
                                                      'placeholder': 'Введите Фамилию'})
        self.fields['avatar'].widget.attrs.update({'type': 'email', 'class': 'form-control',
                                                      'id': 'exampleInputEmail1', 'aria-describedby': 'emailHelp',
                                                      'placeholder': 'Выберите аватар'})


class EnterForm(forms.Form):
    username = forms.CharField(label='Логин')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль')

    def __init__(self, *args, **kwargs):
        super(EnterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'type': 'email', 'class': 'form-control',
                                                     'id': 'exampleInputEmail1', 'aria-describedby': 'emailHelp',
                                                     'placeholder': 'Введите Логин'})

        self.fields['password'].widget.attrs.update({'type': 'password', 'class': 'form-control',
                                                     'id': 'exampleInputPassword1', 'placeholder': 'Пароль'})


class AddBandForm(forms.Form):
    class Meta:
        model = BandModel
        exclude = ['members']

    name = forms.CharField(label="Название")
    # members = forms.ModelMultipleChoiceField(label="Выберите членов группы", queryset=MemberModel.objects.all())  # чтобы только фамилии
    genre = forms.CharField(label="Жанр")
    history = forms.CharField(label="О группе")
    pic = forms.FileField(label="Герб группы", allow_empty_file=True)

    def __init__(self, *args, **kwargs):  # полписи в полях заполнения
        super(AddBandForm, self).__init__(*args, **kwargs)
        self.fields['pic'].widget.attrs.update({'name': 'pic', 'label': 'Загрузить', 'type': 'file',
                                                'class': 'form-control-file', 'id': 'pic'})


class AddMemberForm(forms.Form):
    class Meta:
        model = MemberModel

    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")
    birthdate = forms.DateField(label="Дата рождения")
    deathdate = forms.DateField(label="Дата смерти", required=False)
    country = forms.CharField(label="Страна")
    photo = forms.FileField(label="Фото исполнителя", allow_empty_file=True)

    def __init__(self, *args, **kwargs):
        super(AddMemberForm, self).__init__(*args, **kwargs)
        self.fields['birthdate'].widget.attrs.update({'class': 'form-control', 'placeholder': 'mm/dd/yyyy'})
        self.fields['deathdate'].widget.attrs.update({'class': 'form-control', 'placeholder': 'mm/dd/yyyy'})
        self.fields['photo'].widget.attrs.update({'name': 'photo', 'label': 'Загрузить', 'type': 'file',
                                                  'class': 'form-control-file', 'id': 'photo'})


class MembershipForm(forms.Form):
    class Meta:
        model = MembershipModel
        exclude = ['id_member_FK', 'id_band_FK']

    id_member_FK = forms.ModelChoiceField(queryset=MemberModel.objects.all())
    id_band_FK = forms.ModelChoiceField(queryset=BandModel.objects.all(), required=False)
    function = forms.CharField(label="Должность")
    statuss = forms.BooleanField(label="Все еще в группе?", required=False)


class UpdateProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


'''class UpdateAvaForm(ModelForm):
    class Meta:
        model = UserModel
        fields = ('avatar',)'''

DZ1/templates/band.html
{% extends 'base.html' %}
{% block title %}
    {{ band.name }}
{% endblock %}

{% block body %}
    {% include 'navigator.html' %}
    <div style="display: inline; float: left; width: 70%; padding: 10px 60px;">
        <h1>{{ band.name }}<br>
            <img src="/{{ band.pic }}" style="background-size: 200px"><br>
        </h1>
        <h3>Жанр:</h3> {{ band.genre }}
        <h3>История группы:</h3> {{ band.history }}
        <h3>Участники:</h3>
        {% for member in members %}
            <a href="{% url 'member_url' member.id %}" style="color: #004085;">
                <h5>{{ member.first_name }} {{ member.last_name }}</h5>
            </a>
        {% empty %}
            Туть никого пока что
        {% endfor %}
        {% if username %}
            <div class="add">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
                        name="add_member1">Добавить музыканта
                </button>
            </div>
        {% endif %}
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Добавление музыкантов</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>


                <form method="post" enctype="multipart/form-data" novalidate>
                    <div class="modal-body" style="width: 85%; padding: 15px">
                        {% csrf_token %}
                        <p><label for="id_id_band_FK">Группа:</label>
                            <label name="id_band_FK" required id="id_id_band_FK"
                                   value="{{ band.id }}">{{ band.name }}</label></p>

                        <p><label for="id_id_member_FK">Выберите члена группы:</label>
                            <select name="id_member_FK" required id="id_id_member_FK">
                                <option value selected>------------</option>
                                {% for member in new_members %}
                                    <option value="{{ member.id }}">{{ member.first_name }} {{ member.last_name }}</option>
                                {% endfor %}</select></p>

                        <p><label for="id_function">Должность:</label>
                            <input type="text" name="function" required id="id_function"></p>

                        <p><label for="id_statuss">Все еще в группе?</label>
                            <input type="checkbox" name="statuss" id="id_statuss"></p>

                    </div>


                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-primary" name="add_members">Добавить
                        </button>
                        <div id="probka"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

DZ1/templates/bands_main.html
{% extends 'base.html' %}
{% block title %}Группы{% endblock %}
{% block body %}
    {% include 'navigator.html' %}
    {% if username %}
        <div style="display: inline; float: left; width: 70%; padding: 10px 60px;">
            <div class="add">
                <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#exampleModal"
                        name="add_band1">Добавить музыкальную группу
                </button>
                <a class="btn btn-primary" href="/bands/">Кнопка
                    для тех,
                    кто хочет покрутить
                </a>
            </div>
        </div>
    {% endif %}

    <div id="band-pages">
        {% for band in bands %}
            <ul>
                <div id="row">
                    <div style="float: left; width: 70%; padding-left: 40px;">
                        <div class="media">
                            <a href="{% url 'band_url' band.id %}">
                                <li><h3>{{ band.name|upper }}</h3></li>
                                <img src="/{{ band.pic }}" style="background-size: 200px"><br>
                            </a>
                        </div>
                    </div>
                </div>
            </ul>
        {% endfor %}


        <div class="pagination" style="float: left; width: 70%; padding: 20px 80px;">
    <span class="step-links">
        {% if bands.has_previous %}
            <a href="?page={{ bands.previous_page_number }}">предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ bands.number }} из {{ bands.paginator.num_pages }}.
        </span>

        {% if bands.has_next %}
            <a href="?page={{ bands.next_page_number }}">следующая</a>
        {% endif %}
    </span>
        </div>


        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Добавление группы</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>


                    <form method="post" enctype="multipart/form-data" novalidate>
                        <div class="modal-body" style="width: 85%; padding: 15px">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p><label for="id_members">Выберите членов группы:</label>
                                <select name="members" id="id_members" multiple>
                                    {% for member in members %}
                                        <option value="{{ member.id }}">{{ member.first_name }} {{ member.last_name }}</option>
                                    {% endfor %}
                                </select>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                            <button type="submit" class="btn btn-primary" name="add_band">Добавить
                            </button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

DZ1/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.css">
</head>

<body>

{% block body %}

{% endblock %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>

<script src="{% static "js/endless.js" %}"></script>
<script src="{% static "js/modal_trans.js" %}"></script>

</body>
</html>

DZ1/templates/endReg.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Стартовая страница{% endblock %}
{% block body %}
    {% include 'navigator.html' %}
    <form method="post">
        {% csrf_token %}
    <div class="out" style="margin: 10px 60px;">
        {% if username %}
                <button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#exampleModal"
                        name="band">Группы
                </button>
                <button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#exampleModal"
                        name="member">Музыканты
                </button>
        {% endif %}
    </div>
    </form>
    <form method="post">
        {% csrf_token %}
        {% if not username %}
            <div class="out">
                <div>
                    <button class="btn btn-primary" type="submit" name="sign_in">Войти</button>
                </div>
                <div>
                    <button class="btn btn-primary" type="submit" name="sign_up">Зарегистрироваться</button>
                </div>
            </div>
        {% endif %}
    </form>
{% endblock %}

DZ1/templates/index.html
{% extends 'base.html' %}

{% block title %}Бесконечный скролл и добавление через js{% endblock %}

{% block body %}


    <a href="#" id="myBtn" style="padding-left: 30px;">Добавить новую группу</a>
    <a href="/band/page=1" style="padding-left: 30px;">Вернуться в нормальный режим</a>


    {% if band_list %}
        <div id="bands">
            {% for band in band_list %}
                <div class="row" style="padding-left: 30px;">
                <div class="col">
                    <a href="/band/{{ band.id }}">
                        <h2>{{ band.name }}</h2></a>
                    <img src="/{{ band.pic }}" class="list_image">
                </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <form method="post" enctype="multipart/form-data" id="form_create">
                {% csrf_token %}
                {{ form_create.as_p }}
                <input type="submit" value="Добавить" id="add">
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="/static/js/endless.js"></script>
    <script src="/static/js/create.js"></script>
{% endblock %}

DZ1/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Авторизация{% endblock %}
{% block body %}
    {% include 'navigator.html' %}

    <form method="post">
        {% csrf_token %}
        <div class="sign_in" style="width: 30%; padding: 15px">
            <label style="margin-left: 90px; padding: 5px; font-weight: 700; font-size: 1.5em; color: #405cbf;">Авторизация</label>
            {% if errors != 0 %}
                {% for error in errors %}
                    <br>
                    <div style="color: #ff3d44">{{ error }}.</div>
                {% endfor %}
            {% endif %}

            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">Войти</button>
            <br><br>

            Ещё не зарегистрированы?<br>
            <a href="/registration">
                <button type="button" name="reg" class="btn btn-primary">Перейти к регистрации</button>
            </a><br>
        </div>
    </form>

{% endblock %}

DZ1/templates/main_page.html
{% extends 'base.html' %}
{% block title %}Стартовая страницв{% endblock %}
{% block body %}
    {% include 'navigator.html' %}
{% endblock %}

DZ1/templates/member.html
{% extends 'base.html' %}
{% block title %}
    {{ member.first_name }} {{ member.last_name }}
{% endblock %}

{% block body %}
    {% include 'navigator.html' %}
    <div style="display: inline; float: left; width: 70%; padding: 10px 60px;">
        <h3>{{ member.first_name }} {{ member.last_name }}</h3>
        <img src="/{{ member.photo }}" style="width: 500px">
        <h5>Дата рождения: {{ member.birthdate }} <br>
            Страна: {{ member.country }}</h5>
    </div>
{% endblock %}

DZ1/templates/members.html
{% extends 'base.html' %}
{% block title %}Музыканты{% endblock %}
{% block body %}
    {% include 'navigator.html' %}
    <div style="display: inline; float: left; width: 70%; padding: 10px 40px;">
        <ul>
            {% for member in members %}
                <div class="media">
                    <a href="{% url 'member_url' member.id %}">
                        <li><h3>{{ member.first_name }} {{ member.last_name }}</h3></li>
                    </a>
                </div>
            {% endfor %}

            {% if username %}
                <div class="add">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"
                            name="add_member1">Добавить музыканта
                    </button>
                </div>
            {% endif %}

            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Добавление музыканта</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>

                        <form method="post" enctype="multipart/form-data" novalidate>
                            <div class="modal-body" style="width: 85%; padding: 15px">
                                {% csrf_token %}
                                {{ form.as_p }}
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                                <button type="submit" class="btn btn-primary" name="add_member">Добавить
                                </button>
                                <div id="probka"></div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </ul>
    </div>
{% endblock %}

DZ1/templates/navigator.html
<nav class="navbar navbar-expand-sm bg-dark bg-faded sticky-top">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li>
                <a class="navbar-brand" href="/start/">Музыкальный Флекс</a>
            </li>
            <li>
                <a class="nav-link" href="/band/page=1">Группы</a>
            </li>
            <li>
                <a class="nav-link" href="/member/">Музыканты</a>
            </li>
        </ul>
        <ul class="nav navbar-nav ml-3">
            <form method="post">
                {% csrf_token %}
                {% if username %}
                    <div>
                        <div>
                            <li style="color: white;">
                                <a class="nav-item" style="color: white;" href="/profile/">{{ username }}</a>
                                <button class="btn btn-primary" type="submit" name="logout">Выйти</button>
                            </li>
                        </div>
                    </div>
                {% endif %}
            </form>
        </ul>
    </div>
</nav>

DZ1/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    {{ user.username }}
{% endblock %}

{% block body %}
    {% include 'navigator.html' %}
    <div class="out" style="margin: 10px 60px;">
        <h3>Логин:</h3>
        <h4>{{ user.username }}<br>
            <img src="/static/media/ava/default.jpg" style="size: 100px;"><br></h4>
        <h3>ФИО:</h3> {{ user.last_name }} {{ user.first_name }}
        <h3>Эл.почта:</h3> {{ user.email }}<br>
        <a href="/update_profile">
            <button type="submit" name="update" class="btn btn-primary" id="update">Обновить данные о себе</button>
        </a>
    </div>
{% endblock %}

DZ1/templates/registration.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}
{% block body %}
    {% include 'navigator.html' %}
    <form method="post">
        {% csrf_token %}
        <div class="sign_up" style="width: 30%; padding: 15px">
            <label style="margin-left: 90px; padding: 5px; font-weight: 700; font-size: 1.5em; color: #405cbf;">Регистрация</label>

            {% if errors != 0 %}
                {% for error in errors %}
                    <div style="color: red"><br>{{ error }}.</div>
                {% endfor %}
            {% endif %}

            {{ form.as_p }}
            <br>
            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            <br><br>
            {% if success != 0 %}
                {{ success }}<br>
            {% endif %}

            <a href="/login">
                <button type="button" name="signIn" class="btn btn-primary">Перейти к авторизации</button>
            </a><br>
        </div>
    </form>
{% endblock %}

DZ1/templates/update_ava.html
{% extends 'base.html' %}

{% block title %} Профиль {% endblock %}

{% block body %}
    {% include 'navigator.html' %}
    <div class="out" style="margin: 10px 60px;">

        <h3><a class="button primary" id="update">Обновляем фото:</a></h3>

        <form method="post" enctype="multipart/form-data" id="update_form" class="is-hidden">{% csrf_token %}
            {{ forma.as_p }}
            <input type="submit" value="Обновить">
        </form>
        <a href="/profile">
            <button type="submit" name="updated" class="btn btn-primary" id="updated">Отмена</button>
        </a>
        <script src="/static/js/update.js"></script>
    </div>
{% endblock %}

DZ1/templates/update_profile.html
{% extends 'base.html' %}

{% block title %} Профиль {% endblock %}

{% block body %}
    {% include 'navigator.html' %}
    <div class="out" style="margin: 10px 60px;">

        <h3><a class="button primary" id="update">Обновляем данные о себе:</a></h3>

        <form method="post" enctype="multipart/form-data" id="update_form" class="is-hidden">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Обновить">
        </form>
        <a href="/profile">
            <button type="submit" name="updated" class="btn btn-primary" id="updated">Отмена</button>
        </a>
        <script src="/static/js/update.js"></script>
    </div>
{% endblock %}